# Generated by Django 3.0.3 on 2020-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basictodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datacompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
